name: 'cancercare360'
version: '1.0.0'
config-version: 2

profile: 'cancercare360'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  cancercare360:
    staging:
      +materialized: view
      +schema: silver
    marts:
      +materialized: table
      +schema: gold